package lockfile_test

import (
	"testing"

	"github.com/omni-line/omni-audit/internal/lockfile"
)

func TestParseYarnClassic(t *testing.T) {
	data := []byte(`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abcdef"
  integrity sha512-abc

"@scope/pkg@1.0.0", "@scope/pkg@^1.0.0":
  version "1.0.0"
  resolved "https://registry.npmjs.org/@scope/pkg/-/pkg-1.0.0.tgz#123"
  integrity sha512-xyz
`)
	deps, err := lockfile.ParseYarn(data)
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 2 {
		t.Fatalf("got %d: %+v", len(deps), deps)
	}
	byName := map[string]lockfile.Resolved{}
	for _, d := range deps {
		byName[d.Name] = d
	}
	if byName["lodash"].Version != "4.17.21" {
		t.Fatalf("lodash: %+v", byName["lodash"])
	}
	if byName["@scope/pkg"].URL != "https://registry.npmjs.org/@scope/pkg/-/pkg-1.0.0.tgz" {
		t.Fatalf("scoped: %+v", byName["@scope/pkg"])
	}
}
